/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MyAccountsIndexImport } from './routes/MyAccounts/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MyAccountsIndexRoute = MyAccountsIndexImport.update({
  path: '/MyAccounts/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/MyAccounts/': {
      id: '/MyAccounts/'
      path: '/MyAccounts'
      fullPath: '/MyAccounts'
      preLoaderRoute: typeof MyAccountsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  MyAccountsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/MyAccounts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/MyAccounts/": {
      "filePath": "MyAccounts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
