/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as routeImport } from './routes/__route'

// Create/Update Routes

const routeRoute = routeImport.update({
  id: '/__route',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__route': {
      id: '/__route'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof routeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": [
        "/__route"
      ]
    },
    "/__route": {
      "filePath": "__route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
